# Generated by Django 6.0.7 on 2026-07-21 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appels_offres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Soumissionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=255)),
                ('date_depot', models.DateField()),
                ('statut_conformite', models.CharField(choices=[('a_verifier', 'À vérifier'), ('recevable', 'Recevable'), ('non_recevable', 'Non recevable'), ('conforme_technique', 'Conforme technique'), ('non_conforme_technique', 'Non conforme technique')], default='a_verifier', max_length=30)),
                ('motif_rejet', models.TextField(blank=True, null=True)),
                ('prix_lu_publiquement', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('prix_corrige', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('rang', models.PositiveIntegerField(blank=True, null=True)),
                ('qualification_verifiee', models.BooleanField(default=False)),
                ('qualification_conforme', models.BooleanField(blank=True, null=True)),
                ('statut_final', models.CharField(choices=[('en_cours', 'En cours'), ('retenu', 'Retenu (attributaire proposé)'), ('ecarte', 'Écarté')], default='en_cours', max_length=20)),
                ('appel_offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissionnaires', to='appels_offres.appeloffre')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=2, max_digits=6)),
                ('justification', models.TextField()),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('critere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appels_offres.criteregrille')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('soumissionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='soumissionnaires.soumissionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='DonneeExtraite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_extraite', models.TextField()),
                ('justification_ia', models.TextField(blank=True)),
                ('critere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appels_offres.criteregrille')),
                ('soumissionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donnees_extraites', to='soumissionnaires.soumissionnaire')),
            ],
        ),
    ]
