# Generated by Django 6.0.7 on 2026-08-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soumissionnaires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soumissionnaire',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soumissionnaire',
            name='beneficiaires_effectifs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soumissionnaire',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='soumissionnaire',
            name='nationalite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soumissionnaire',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='soumissionnaire',
            name='date_depot',
            field=models.DateField(auto_now_add=True),
        ),
    ]
