# Generated by Django 6.0.7 on 2026-08-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soumissionnaires', '0002_soumissionnaire_adresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soumissionnaire',
            name='texte_extrait',
            field=models.TextField(blank=True, null=True),
        ),
    ]
