# Generated by Django 6.0.7 on 2026-08-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soumissionnaires', '0003_soumissionnaire_texte_extrait'),
    ]

    operations = [
        migrations.AddField(
            model_name='soumissionnaire',
            name='fichier_dossier',
            field=models.FileField(blank=True, null=True, upload_to='dossiers_candidats/'),
        ),
        migrations.AlterField(
            model_name='soumissionnaire',
            name='statut_final',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('retenu', 'Retenu'), ('ecarte', 'Écarté')], default='en_cours', max_length=20),
        ),
    ]
