# Generated by Django 6.0.7 on 2026-08-06 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soumissionnaires', '0004_soumissionnaire_fichier_dossier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soumissionnaire',
            name='fichier_dossier',
        ),
    ]
