# Generated by Django 6.0.7 on 2026-08-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels_offres', '0006_alter_criteregrille_options'),
        ('soumissionnaires', '0005_remove_soumissionnaire_fichier_dossier'),
    ]

    operations = [
        migrations.AddField(
            model_name='soumissionnaire',
            name='fichier_dossier',
            field=models.FileField(blank=True, null=True, upload_to='dossiers_candidats/'),
        ),
        migrations.AlterField(
            model_name='donneeextraite',
            name='justification_ia',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='donneeextraite',
            name='valeur_extraite',
            field=models.TextField(default='Non fourni'),
        ),
        migrations.AlterUniqueTogether(
            name='donneeextraite',
            unique_together={('soumissionnaire', 'critere')},
        ),
    ]
