# Generated by Codex on 2026-08-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soumissionnaires", "0006_soumissionnaire_fichier_dossier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="soumissionnaire",
            name="prix_corrige",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name="soumissionnaire",
            name="prix_lu_publiquement",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
