# Generated by Django 6.0.7 on 2026-08-10 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soumissionnaires', '0007_alter_soumissionnaire_prix_corrige_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='soumissionnaire',
            name='date_depot_dossier',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soumissionnaire',
            name='depose_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_deposes', to=settings.AUTH_USER_MODEL),
        ),
    ]
