# Generated by Django 6.0.7 on 2026-08-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiqueaction',
            name='utilisateur_nom',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='historiqueaction',
            name='utilisateur_role',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
