# Generated by Django 6.0.7 on 2026-07-17 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppelOffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('titre', models.CharField(max_length=255)),
                ('date_publication', models.DateField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('grille_en_attente', 'Grille en attente de validation'), ('en_cours', "En cours d'évaluation"), ('juge', 'Jugé'), ('cloture', 'Clôturé')], default='brouillon', max_length=30)),
                ('document_source', models.FileField(blank=True, null=True, upload_to='cahiers_des_charges/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CritereGrille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('categorie', models.CharField(choices=[('technique', 'Technique'), ('financier', 'Financier'), ('administratif', 'Administratif')], max_length=20)),
                ('note_max', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('appel_offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteres', to='appels_offres.appeloffre')),
            ],
        ),
    ]
