# Generated by Django 6.0.7 on 2026-07-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels_offres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeloffre',
            name='texte_extrait',
            field=models.TextField(blank=True, null=True),
        ),
    ]
