# Generated by Django 6.0.7 on 2026-07-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels_offres', '0002_appeloffre_texte_extrait'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteregrille',
            name='source',
            field=models.CharField(choices=[('ia', "Généré par l'IA"), ('manuel', 'Ajouté manuellement')], default='ia', max_length=10),
        ),
        migrations.AddField(
            model_name='criteregrille',
            name='valide',
            field=models.BooleanField(default=False),
        ),
    ]
