# Generated by Django 6.0.7 on 2026-07-29 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels_offres', '0003_criteregrille_source_criteregrille_valide'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteregrille',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_criteres', to='appels_offres.criteregrille'),
        ),
        migrations.AddField(
            model_name='criteregrille',
            name='type_groupe',
            field=models.CharField(choices=[('eliminatoire', 'Éliminatoire'), ('notable', 'Notable')], default='notable', max_length=20),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='texte_extrait',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
