# Generated by Django 6.0.7 on 2026-07-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels_offres', '0004_criteregrille_parent_criteregrille_type_groupe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeloffre',
            name='texte_extrait',
            field=models.TextField(blank=True, null=True),
        ),
    ]
