# Generated by Django 6.0.7 on 2026-08-06 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appels_offres', '0005_alter_appeloffre_texte_extrait'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criteregrille',
            options={'ordering': ['parent__id', 'id']},
        ),
    ]
