# Generated by Django 6.0.7 on 2026-07-21 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appels_offres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesVerbal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé et signé')], default='brouillon', max_length=20)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='proces_verbaux/')),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('appel_offre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proces_verbal', to='appels_offres.appeloffre')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
